on: push
name: Build
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    - name: go mod download
      uses: cedrickring/golang-action@1.1.0
      env:
        GO111MODULE: "on"
      with:
        args: go mod download
    - name: packr2
      uses: cedrickring/golang-action@1.1.0
      env:
        GO111MODULE: "on"
      with:
        args: packr2
    - name: go build
      uses: cedrickring/golang-action@1.1.0
      env:
        GO111MODULE: "on"
      with:
        args: go build